### ISSUE TITLE
V8 - Erroare validare factura furnizor 

### ISSUE THREAD

**Issue by sharkutz** [odoo-romania/l10n-romania#109]
Dupa ultimul update nu se mai poate valida factura de la furnizor.
Urmatoarea erroare apare in loguri:
2015-08-22 07:43:00,317 20096 ERROR neozivdb_production openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odooV8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odooV8/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odooV8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/odooV8/openerp/http.py", line 1111, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/odooV8/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/odooV8/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 183, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 177, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/odooV8/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3561, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/odooV8/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/odooV8/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/odooV8/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/odooV8/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/addons/account/account_invoice.py", line 919, in action_move_create
    move = account_move.with_context(ctx_nolang).create(move_vals)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/odooV8/addons/account/account.py", line 1404, in create
    result = super(account_move, self).create(cr, uid, vals, c)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 4078, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 4263, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/opt/odoo/odooV8/openerp/osv/fields.py", line 811, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/addons/account/account_move_line.py", line 1352, in create
    result = super(account_move_line, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 4078, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 4216, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/odooV8/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "column "currency_reevaluation" of relation "account_move_line" does not exist
LINE 1: ...nt_move_line" ("id", "company_id", "currency_id", "currency_...
                                                             ^
" while evaluating
u'action_move_create()'
2015-08-22 07:43:01,467 20096 ERROR neozivdb_production openerp.sql_db: Programming error: column "currency_reevaluation" of relation "account_move_line" does not exist
LINE 1: ...nt_move_line" ("id", "company_id", "currency_id", "currency_...
                                                             ^
, in query INSERT INTO "account_move_line" ("id", "company_id", "currency_id", "currency_reevaluation", "date_maturity", "not_deductible", "partner_id", "blocked", "asset_id", "centralisation", "journal_id", "tax_code_id", "state", "debit", "ref", "analytic_account_id", "account_id", "period_id", "date_created", "date", "move_id", "product_id", "tax_amount", "name", "product_uom_id", "credit", "amount_currency", "quantity", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('account_move_line_id_seq'), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2015-08-22 07:43:01,468 20096 ERROR neozivdb_production openerp.http: "column "currency_reevaluation" of relation "account_move_line" does not exist
LINE 1: ...nt_move_line" ("id", "company_id", "currency_id", "currency_...
                                                             ^
" while evaluating
u'action_move_create()'

**Comment by sharkutz** [comment]
Am dezinstalat modulul l10n_ro_currency_reevaluation si merge validarea facturilor.

**Comment by feketemihai** [comment]
Luni dupa masa a nai fac un pr...sa vad de ce nu s-a facut ok...e pentru facturile in valuta sa calculeze residual fara actualizari de curs valutar.

**Comment by feketemihai** [comment]
La mine e ok...nu am nici o eroare...campul este definit:

https://github.com/odoo-romania/l10n-romania/blob/8.0/l10n_ro_currency_reevaluation/account.py#L38

porneste serverul cu --update=all si vezi dupa aceea...

**Comment by sharkutz** [comment]
am incercat in mod repetat si acum dau de alta eroare:

2015-08-25 19:06:51,912 3541 ERROR neoziv openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odooV8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odooV8/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odooV8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/odooV8/openerp/http.py", line 1111, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/odooV8/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/odooV8/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 183, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 177, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/odooV8/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3561, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/odooV8/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/odooV8/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/odooV8/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/odooV8/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/odooV8/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/addons/account/account_invoice.py", line 927, in action_move_create
    inv.with_context(ctx).write(vals)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odooV8/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3778, in write
    self._write(old_vals)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 4025, in _write
    recs.recompute()
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 5703, in recompute
    name: rec[name] for name in names
  File "/opt/odoo/odooV8/openerp/models.py", line 5703, in <dictcomp>
    name: rec[name] for name in names
  File "/opt/odoo/odooV8/openerp/models.py", line 5587, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odooV8/openerp/fields.py", line 817, in __get__
    self.determine_value(record)
  File "/opt/odoo/odooV8/openerp/fields.py", line 895, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/odooV8/openerp/fields.py", line 875, in compute_value
    self._compute_value(records)
  File "/opt/odoo/odooV8/openerp/fields.py", line 867, in _compute_value
    self.compute(records)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 398, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odooV8/addons/account/account_invoice.py", line 137, in _compute_residual
    line_amount = from_currency.compute(line.amount_residual, self.currency_id)
  File "/opt/odoo/odooV8/openerp/fields.py", line 817, in __get__
    self.determine_value(record)
  File "/opt/odoo/odooV8/openerp/fields.py", line 910, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3232, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3177, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3343, in _read_from_database
    res2 = self._columns[fs[0]].get(cr, self._model, ids, fs, user, context=context, values=result)
  File "/opt/odoo/odooV8/openerp/osv/fields.py", line 1467, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/custom_addons/l10n_ro_currency_reevaluation/account.py", line 112, in _amount_residual
    if move_line.journal_id.posting_policy == 'storno':
ValueError: "'account.journal' object has no attribute 'posting_policy'" while evaluating
u'action_move_create()'

**Comment by feketemihai** [comment]
O sa pun currency reevaluation sa depinda si de storno...maine dimineata...



Mihai Fekete
ODOO Specialist

Forest and Biomass Services Romania
+4(0) 746 - 028 477


-------- Original message --------

**Comment by sharkutz** [comment]
Am incercat sa dezinstalez modulul de storno dar tot nu merge.

**Comment by feketemihai** [comment]
Fix in #111
