### ISSUE TITLE
V8  ERROR for l10n_ro_account_bank_statement.view_account_statement_operation_template_search

### ISSUE THREAD

**Issue by sharkutz** [odoo-romania/l10n-romania#110]
2015-08-22 14:48:19,782 13208 ERROR neoziv openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odooV8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odooV8/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odooV8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 1247, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/opt/odoo/odooV8/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/web_debranding/models/ir_actions.py", line 11, in read
    cr, uid, ids, fields=fields, context=context, load=load)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/addons/base/ir/ir_actions.py", line 325, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3142, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3177, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3356, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/odooV8/openerp/osv/fields.py", line 1467, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/odooV8/openerp/addons/base/ir/ir_actions.py", line 267, in _search_view
    'search', context=context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 1545, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/addons/base/ir/ir_ui_view.py", line 841, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/addons/base/ir/ir_ui_view.py", line 369, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `company_id` does not exist

Error context:
View `account.statement.operation.template.search`
[view_id: 366, xml_id: account.view_account_statement_operation_template_search, model: account.statement.operation.template, parent_id: n/a]

**Comment by feketemihai** [comment]
De cand a fost acceptat l10n_ro in v8 si v9 cel din odoo romania, eu folosesc branchul  de odooplus modulele din odoo-romania/extra pentru drepturi de acces pe companie in bank.statement.operation.template si product.category.

**Comment by sharkutz** [comment]
nu mai am erroare related to : Field company_id
