### ISSUE TITLE
[V8] l10n_ro_account_report - error 

### ISSUE THREAD

**Issue by sharkutz** [odoo-romania/l10n-romania#86]
Hi, 
I have this error. Is this something know or my system is configured badly ??

Traceback (most recent call last):
  File "/opt/odoo/odooV8/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odooV8/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odooV8/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 939, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom_addons/l10n_ro_account_report/wizard/d394.py", line 586, in create_xml
    xml_data = self._get_datas(cursor, user, ids, context=context)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom_addons/l10n_ro_account_report/wizard/d394.py", line 84, in _get_datas
    _('You need to define your Job Position.'))
except_orm: (u'Error!', u'You need to define your Job Position.')

**Comment by feketemihai** [comment]
Hi,

You just need to put something in the field JOB POSITION available in the partner associated with your user or with the user that generates the D394 report.

Please tell me if it's ok after.


Mihai Fekete
Sent from Samsung Mobile.


-------- Original message --------
From: sharkutz
Date:26/03/2015 23:19 (GMT+02:00)
To: odoo-romania/l10n-romania
Subject: [l10n-romania] [V8] l10n_ro_account_report - error (#86)


Hi,
I have this error. Is this something know or my system is configured badly ??

Traceback (most recent call last):
File "/opt/odoo/odooV8/openerp/http.py", line 530, in handle_exception
return super(JsonRequest, self).handle_exception(exception)
File "/opt/odoo/odooV8/openerp/http.py", line 567, in dispatch
result = self._call_function(*self.params)
File "/opt/odoo/odooV8/openerp/http.py", line 303, in _call_function
return checked_call(self.db, *args, *kwargs)
File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
return f(dbname, args, *kwargs)
File "/opt/odoo/odooV8/openerp/http.py", line 300, in checked_call
return self.endpoint(a, *kw)
File "/opt/odoo/odooV8/openerp/http.py", line 796, in __call
return self.method(args, *kw)
File "/opt/odoo/odooV8/openerp/http.py", line 396, in response_wrap
response = f(args, *kw)
File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 939, in call_button
action = self._call_kw(model, method, args, {})
File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 927, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/custom_addons/l10n_ro_account_report/wizard/d394.py", line 586, in create_xml
xml_data = self._get_datas(cursor, user, ids, context=context)
File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/custom_addons/l10n_ro_account_report/wizard/d394.py", line 84, in _get_datas
_('You need to define your Job Position.'))
except_orm: (u'Error!', u'You need to define your Job Position.')

-

**Comment by sharkutz** [comment]
Thank you, no more error
